### PR TITLE
Fix URL.

### PR DESCRIPTION
**Pull request by icemac**

### CODE REVIEW

**Comment by icemac** [comment]
@petschki Hm, the Jenkins bot did not offer to run the tests and there were not run any tests on TravisCI either. Does this mean this still has to be configured?

**Comment by petschki** [comment]
@icemac true! I'll create an issue for that. Someone with permissions has to enable the new repo on travis-ci and mr-roboto seems not taking this into account, though I've changed the url in buildout.coredev/sources.cfg

**Comment by gforcada** [comment]
@petschki mr.roboto needs to add the hooks to the repository. I started that right now.

**Comment by petschki** [comment]
Great, thank you @gforcada!

**Pull request merged**
